import { expect, test, type Locator } from "@playwright/test"

test.beforeEach(async ({ page }, testInfo) => {
  if (testInfo.title === "settings save failures retain the edited value and allow retry") {
    await page.route("**/src/demo.ts*", async route => {
      const response = await route.fetch()
      const original = await response.text()
      expect(original).toContain("identity.display_name = params.display_name;")
      const body = original.replace('identity.display_name = params.display_name;', 'if (params.display_name === "Fail") throw new Error("Sample save failure"); identity.display_name = params.display_name;')
      await route.fulfill({ response, body })
    })
  }
  await page.goto("/?demo=teal")
  await expect(page.getByRole("heading", { name: "Alice Chen", exact: true })).toBeVisible()
})

test("demo variants, message sending, and search use sample data", async ({ page }) => {
  await expect(page.getByText("Design demo", { exact: true })).toBeVisible()
  await expect(page.locator("html")).toHaveAttribute("data-accent", "teal")
  await page.screenshot({ path: "test-results/demo-teal.png" })
  await page.getByRole("button", { name: "Blue", exact: true }).click()
  await expect(page.locator("html")).toHaveAttribute("data-accent", "blue")
  await page.screenshot({ path: "test-results/demo-blue.png" })
  await page.getByRole("textbox", { name: "Message", exact: true }).fill("A sample message")
  await page.getByRole("button", { name: "Send message", exact: true }).click()
  await expect(page.locator(".history")).toContainText("A sample message")
  await page.getByRole("button", { name: "Search messages", exact: true }).click()
  await page.getByRole("textbox", { name: "Search text" }).fill("Saturday")
  await page.getByRole("button", { name: "Search", exact: true }).click()
  await page.locator(".search-result").first().click()
  await expect(page.getByRole("heading", { name: "Alice Chen", exact: true })).toBeVisible()
  expect(await page.evaluate(() => localStorage.getItem("meshtalk-selection"))).toBeNull()
  expect(await page.evaluate(() => localStorage.getItem("meshtalk-accent"))).toBeNull()
})

test("settings fill the window, save changes, preserve edits, and restore focus", async ({ page }) => {
  await page.getByRole("button", { name: "Settings", exact: true }).click()
  const settings = page.getByRole("dialog", { name: "Settings", exact: true })
  await expect(settings).toBeVisible()
  const box = await settings.boundingBox()
  expect(box?.width).toBe(1100)
  expect(box?.height).toBe(760)
  await expect(page.getByRole("heading", { name: "Profile", exact: true })).toBeVisible()
  await page.screenshot({ path: "test-results/settings-profile.png" })
  await page.getByLabel("Display name", { exact: true }).fill("Casey")
  await page.getByRole("button", { name: "Save name" }).click()
  await expect(page.getByRole("status", { name: "Settings status" })).toContainText("Display name saved")
  await page.getByLabel("Display name", { exact: true }).fill("Unsaved edit")
  await page.getByRole("switch", { name: "Launch at login" }).check()
  await expect(page.getByRole("status", { name: "Settings status" })).toContainText("Changes saved")
  await expect(page.getByLabel("Display name", { exact: true })).toHaveValue("Unsaved edit")
  await page.getByRole("button", { name: "Appearance", exact: true }).click()
  await page.getByRole("button", { name: "Dark", exact: true }).click()
  await expect(page.locator("html")).toHaveAttribute("data-theme", "dark")
  await page.getByRole("button", { name: "Signal-inspired blue", exact: true }).click()
  await expect(page.locator("html")).toHaveAttribute("data-accent", "blue")
  await page.screenshot({ path: "test-results/settings-appearance-dark.png" })
  await page.getByRole("button", { name: "Notifications", exact: true }).click()
  await page.screenshot({ path: "test-results/settings-notifications.png" })
  await page.getByRole("switch", { name: "Enable notifications", exact: true }).uncheck()
  await expect(page.getByRole("switch", { name: "Messages", exact: true })).toBeDisabled()
  await page.getByRole("button", { name: "Privacy", exact: true }).click()
  await expect(page.getByLabel("Analytics level")).toHaveValue("off")
  await page.getByRole("button", { name: "Back to chats" }).click()
  await expect(settings).not.toBeVisible()
  await expect(page.getByRole("button", { name: "Settings", exact: true })).toBeFocused()
  await expect(page.locator(".user-panel")).toContainText("Casey")
  await page.screenshot({ path: "test-results/demo-dark.png" })
})

test("technical connection controls remain visible and functional", async ({ page }) => {
  await page.getByRole("button", { name: "Settings", exact: true }).click()
  await page.getByRole("button", { name: "Connection", exact: true }).click()
  await expect(page.getByLabel("Server URL")).toHaveValue("wss://meshtalk-control.qincai.xyz/v1/rendezvous")
  await expect(page.getByText("Remote discovery connected", { exact: true })).toBeVisible()
  await page.screenshot({ path: "test-results/settings-connection.png" })
  await page.getByRole("switch", { name: "Enable remote discovery" }).uncheck()
  await expect(page.getByText("Local network only", { exact: true })).toBeVisible()
  await page.getByRole("switch", { name: "Enable remote discovery" }).check()
  await expect(page.getByText("Remote discovery connected", { exact: true })).toBeVisible()
  await page.getByLabel("Manual control addresses").fill("203.0.113.10")
  await page.getByRole("button", { name: "Save addresses" }).first().click()
  await expect(page.getByText("203.0.113.10", { exact: true })).toBeVisible()
  await page.getByRole("button", { name: "Diagnostics", exact: true }).click()
  await page.getByRole("button", { name: "Refresh diagnostics", exact: true }).click()
  await expect(page.locator(".diagnostic-output")).toContainText('"demo": true')
  await page.keyboard.press("Escape")
  await expect(page.getByRole("dialog", { name: "Settings", exact: true })).not.toBeVisible()
})

test("narrow settings and dialogs remain usable with keyboard navigation", async ({ page }) => {
  await page.setViewportSize({ width: 640, height: 480 })
  await page.getByRole("button", { name: "Settings", exact: true }).click()
  await page.getByRole("button", { name: "Connection", exact: true }).click()
  await page.getByLabel("Manual STUN addresses").scrollIntoViewIfNeeded()
  await expect(page.getByLabel("Manual STUN addresses")).toBeVisible()
  expect(await page.locator(".settings-content").evaluate(el => el.scrollWidth <= el.clientWidth)).toBe(true)
  await page.screenshot({ path: "test-results/settings-narrow.png" })
  await page.getByRole("button", { name: "Rooms", exact: true }).click()
  await page.getByRole("button", { name: "Leave…", exact: true }).click()
  const confirm = page.getByRole("dialog", { name: "Leave Weekend plans?" })
  await expect(confirm).toBeVisible()
  await page.keyboard.press("Escape")
  await expect(confirm).not.toBeVisible()
  await expect(page.getByRole("dialog", { name: "Settings", exact: true })).toBeVisible()
  await page.keyboard.press("Escape")
  await page.getByRole("button", { name: "New conversation", exact: true }).click()
  await page.getByRole("button", { name: /Create a group/ }).click()
  await expect(page.getByRole("dialog", { name: "Create a group", exact: true })).toBeVisible()
  await page.keyboard.press("Escape")
  await expect(page.getByRole("button", { name: "Send message", exact: true })).toBeVisible()
})

test("empty conversation searches explain how to recover", async ({ page }) => {
  await page.getByRole("textbox", { name: "Search conversations" }).fill("Nobody with this name")
  await expect(page.getByRole("heading", { name: "No matches", exact: true })).toBeVisible()
  await expect(page.getByText("Try a different name.")).toBeVisible()
})

// Browser checks verify CSS and wheel routing, not macOS native rubber-banding.
test("scroll panels disable boundary effects without blocking wheel scrolling", async ({ page }) => {
  async function wheelOver(panel: Locator, delta: number) {
    await panel.evaluate(el => {
      el.removeAttribute("data-wheel-settled")
      el.addEventListener("wheel", () => {
        requestAnimationFrame(() => requestAnimationFrame(() => el.setAttribute("data-wheel-settled", "true")))
      }, { once: true, passive: true })
    })
    await page.mouse.wheel(0, delta)
    await expect(panel).toHaveAttribute("data-wheel-settled", "true")
  }
  const rows = Array.from({ length: 28 }, (_, index) => ({
    message_id: `scroll-${index}`,
    sender_id: "alice",
    content: index === 0 ? Array.from({ length: 18 }, (_, line) => `Sample checklist line ${line + 1}`).join("\n") : `Sample message ${index + 1}`,
    created_at: 1791626400 + index * 90,
  }))
  await page.route("**/src/demo.ts*", async route => {
    const response = await route.fetch()
    const original = await response.text()
    expect(original).toContain("const preferences =")
    await route.fulfill({ response, body: original.replace("const preferences =", `messages.alice = ${JSON.stringify(rows)};\nconst preferences =`) })
  })
  await page.reload()
  const history = page.locator(".history")
  await expect(history.locator(".msg")).toHaveCount(rows.length)
  const maximum = await history.evaluate(el => el.scrollHeight - el.clientHeight)
  expect(maximum).toBeGreaterThan(1000)
  for (const selector of ["html", "body", "#root", ".sidebar nav", ".history"]) {
    await expect(page.locator(selector)).toHaveCSS("overscroll-behavior-y", "none")
  }
  await history.evaluate(el => { el.scrollTop = 0 })
  const box = (await history.boundingBox())!
  await page.mouse.move(box.x + box.width / 2, box.y + box.height / 2)
  await wheelOver(history, 180)
  await expect.poll(() => history.evaluate(el => el.scrollTop)).toBeGreaterThan(0)
  await history.evaluate(el => { el.scrollTop = el.scrollHeight })
  await wheelOver(history, 180)
  expect(await history.evaluate(el => el.scrollTop)).toBe(maximum)
  await wheelOver(history, -180)
  await expect.poll(() => history.evaluate(el => el.scrollTop)).toBeLessThan(maximum)
  await history.evaluate(el => { el.scrollTop = 0 })
  await wheelOver(history, -180)
  expect(await history.evaluate(el => el.scrollTop)).toBe(0)

  await page.getByRole("button", { name: "Search messages", exact: true }).click()
  await page.getByRole("textbox", { name: "Search text", exact: true }).fill("Sample")
  await page.getByRole("button", { name: "Search", exact: true }).click()
  const result = page.locator(".search-result p").first()
  const dialog = page.getByRole("dialog", { name: "Search messages", exact: true })
  await expect(result).toBeVisible()
  await expect(result).toHaveCSS("overscroll-behavior-y", "none")
  await expect(dialog).toHaveCSS("overscroll-behavior-y", "none")
  const resultMaximum = await result.evaluate(el => el.scrollHeight - el.clientHeight)
  expect(resultMaximum).toBeGreaterThan(0)
  expect(await dialog.evaluate(el => el.scrollHeight - el.clientHeight)).toBeGreaterThan(0)
  const resultBox = (await result.boundingBox())!
  await page.mouse.move(resultBox.x + resultBox.width / 2, resultBox.y + resultBox.height / 2)
  await wheelOver(result, 60)
  await expect.poll(() => result.evaluate(el => el.scrollTop)).toBeGreaterThan(0)
  await result.evaluate(el => { el.scrollTop = el.scrollHeight })
  await wheelOver(result, 240)
  expect(await result.evaluate(el => el.scrollTop)).toBe(resultMaximum)
  expect(await dialog.evaluate(el => el.scrollTop)).toBe(0)
})

test("settings save failures retain the edited value and allow retry", async ({ page }) => {
  await page.getByRole("button", { name: "Settings", exact: true }).click()
  await page.getByLabel("Display name", { exact: true }).fill("Fail")
  await page.getByRole("button", { name: "Save name" }).click()
  await expect(page.getByRole("alert")).toContainText("Sample save failure")
  await expect(page.getByLabel("Display name", { exact: true })).toHaveValue("Fail")
  await expect(page.getByRole("button", { name: "Save name" })).toBeEnabled()
  await page.getByLabel("Display name", { exact: true }).fill("Recovered")
  await page.getByRole("button", { name: "Save name" }).click()
  await expect(page.getByRole("status", { name: "Settings status" })).toContainText("Display name saved")
  await expect(page.getByRole("alert")).toHaveCount(0)
})
